{% set version = "3.4.1" %}

package:
  name: r
  version: {{ version }}

build:
  number: 0
  skip: true  # [win32]

requirements:
  run:
    - r-base {{ version }}
    - r-recommended {{ version }}

# test to force the test env creation
# if any dependency is missing the test env creation will fail
test:
  commands:
    - $R -e "library('MASS')"  # [not win]
    - "\"%R%\" -e \"library('MASS')\""  # [win]

about:
  home: http://www.r-project.org/
  license: GPL-3.0
  summary: 'R is a free software environment for statistical computing and graphics.'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
